import React, {useEffect } from 'react';
import ReactDOM from 'react-dom';
import { Link } from 'react-router-dom';
import Login from './auth/Login';
import Header from './Header';
import WormList from './WormList';
import Worm from './Worm';
import { Button, Textfield } from '@material-ui/core';
import Earth from 'images/earth_icon.png';
import { useStore } from 'react-redux';
import store from '../store/store';

import { createStore } from 'redux';
import WormCreator from './WormCreator';
import { fetchWorms } from '../features/wormList/wormListSlice';
import { useDispatch } from 'react-redux';
require('isomorphic-fetch');

const mainImgBG = {
    backgroundImage: "url('worm_27.png') !important",
}
const backgroundGrey = {
    backgroundColor: '#232d3d',
    display: 'flex',
    flexDirection: 'row',
    justifyContent: 'center',
    alignItems: 'center'
}
const popCard = {
    margin: "-60px 30px 0px",
    boxShadow: "1px -3px 47px 0px rgba(233,218,218,0.75)",
    WebkitBoxShadow:"1px -3px 47px 0px rgba(233,218,218,0.75)",
    MozBoxShadow: "1px -3px 47px 0px rgba(233,218,218,0.75)",
    position: 'relative',
    top: "-20px",
    width: 'fit-content',
    padding: "15px",
    zIndex: '6',
    background: "linear-gradient(to right, #de1245 0%, #ffbc15 100%)",
    color: "#eee",
    borderRadius: '7px',
    width: '66%',
    fontWeight: '600',
}
const note = {
    fontStyle: 'italic',
    
}
const fiftyWidth = {width: '50%',}
const leftRem = {marginLeft: '1rem', color: '#eee', width: "70%",}
const leftTwoRem = {marginLeft: '2rem', color: '#eee', width: "70%",}

const wormGallaryHeader = {
    textAlign: 'center',
    marginBottom: '10rem',
}

const flexCol = {
    display: 'flex',
    flexDirection: 'column',
    justifyContent: 'center',
    alignItems: 'center',
}
const textCenter = {
    textAlign: 'center',
    width: '67%',
}
const flexRow = {
    display: 'flex',
    flexDirection: 'row',
    justifyContent: 'space-around',
    alignItems: 'center',
    width: '100%',
}
const aboutHr = {
    color: "#eee",
    height: "1px",
    border: "1px solid #eee",
    width: "50%",
}
const aboutUsHeader = {
    marginBottom: '2.5em',
}
const tryItOut = {
    marginTop: '2.5em',
}

export default function Home(props){
    const dispatch = useDispatch();
      return ( 
        <div >
            <div className="mainImgBG flex-col">
             <Header />
            </div>
            <div style={backgroundGrey}>
                <div style={popCard}>
                    <Login />
                    <hr />
                    <div>
                        <section>
                            <h2 style={aboutUsHeader}>About us</h2>
                            <div style={flexCol}>
                                <div style={flexRow}>
                                    <div style={flexCol}>
                                        <div className="no-trees-bg">
                                        </div>
                                        <p>We don't plant trees.</p>
                                    </div>
                                    <div style={flexCol}>
                                        <div className="no-rice-bg">
                                        </div>
                                        <p>We don't give away rice.</p>
                                    </div>
                                </div>
                                <hr style={aboutHr} />
                                <div style={flexCol}>
                                    <div className="yes-worm-bg">
                                    </div>
                                    <p>We let you generate worms.</p>
                                </div>
                            </div>
                        </section>
                        <hr />
                        <section>
                            <h2>Why we're here</h2>
                            <p style={leftRem}>Here at wormcreate.com, we believe that the world needs more worms.  We aim to put the power in the hands of the people to make yourself an artist.  Our intent is to have as many as possible worms generated by you all, and for these worms to impose their presence across the metaverse.</p>
                        </section>
                        <hr />
                        <section>
                            <h2>A Note from The Creator of WormCreator</h2>
                            <h4 style={Object.assign({}, leftRem, note)}>{'>'}In Case You were Wondering, I do Consider Myself the 'Johannes Guetenberg of Generating Worms'</h4>
                            <p style={Object.assign({}, leftTwoRem, note)}>{'>'}The every-day average person deserves to harness the power of p5.js to generate aesthetically pleasing worms.  It is just, and a God-given right.  Generative art may be more cool and impressive, but user-generated art is more fun, and that is why I followed like one or two p5.js guides and then created a variation of a simple program that is found in many 'how to p5' blog posts and put it on a Ruby on Rails application with a React/Redux frot-end that uses Material-UI.</p>
                            <p style={Object.assign({}, leftTwoRem, note)}>{'>'}Do with this what you will, but remember: with great power comes great responsibility. </p>
                        </section>
                        <hr />
                        <section style={flexCol}>
                            <h2 style={tryItOut}>Try it out</h2>
                            <p style={textCenter}>Just click or tap on the screen to start creating a worm.  Hold down and drag.  Release to complete the worm.</p>
                            <WormCreator dispatch={dispatch} />
                            
                            <div id="newWormContainer"></div>
                        </section>
                        <hr />
                    </div>
                    <div>
                        <section>
                            <h2 style={wormGallaryHeader}>Worm Gallary</h2>
                            <WormList />
                        </section>
                    </div>
                </div>
            </div>
        </div>
      );
  }
